/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateSensorArgs } from "./CreateSensorArgs";
import { UpdateSensorArgs } from "./UpdateSensorArgs";
import { DeleteSensorArgs } from "./DeleteSensorArgs";
import { SensorFindManyArgs } from "./SensorFindManyArgs";
import { SensorFindUniqueArgs } from "./SensorFindUniqueArgs";
import { Sensor } from "./Sensor";
import { SensorService } from "../sensor.service";

@graphql.Resolver(() => Sensor)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SensorResolverBase {
  constructor(
    protected readonly service: SensorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Sensor",
    action: "read",
    possession: "any",
  })
  async _sensorsMeta(
    @graphql.Args() args: SensorFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Sensor])
  @nestAccessControl.UseRoles({
    resource: "Sensor",
    action: "read",
    possession: "any",
  })
  async sensors(
    @graphql.Args() args: SensorFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Sensor[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Sensor",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Sensor, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Sensor",
    action: "read",
    possession: "own",
  })
  async sensor(
    @graphql.Args() args: SensorFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Sensor | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Sensor",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Sensor)
  @nestAccessControl.UseRoles({
    resource: "Sensor",
    action: "create",
    possession: "any",
  })
  async createSensor(
    @graphql.Args() args: CreateSensorArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Sensor> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Sensor",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Sensor"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Sensor)
  @nestAccessControl.UseRoles({
    resource: "Sensor",
    action: "update",
    possession: "any",
  })
  async updateSensor(
    @graphql.Args() args: UpdateSensorArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Sensor | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Sensor",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Sensor"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Sensor)
  @nestAccessControl.UseRoles({
    resource: "Sensor",
    action: "delete",
    possession: "any",
  })
  async deleteSensor(
    @graphql.Args() args: DeleteSensorArgs
  ): Promise<Sensor | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
